apiVersion: v1
kind: Service
metadata:
  labels:
    name: microservice
  name: microservice
spec:
  ports:
    - port: 3050
  selector:
    name: microservice

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: microservice
  name: microservice
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: microservice
    spec:
      containers:
      - name: microservice
        image: <notset>
        args:
          - start
        env:
          - name: PORT
            value: "3050"

        ports:
          - containerPort: 3050

      restartPolicy: Always
